declare @date 

DECLARE	@FROMDATE_1		VARCHAR(8)
DECLARE	@TODATE_1		VARCHAR(8)	
DECLARE	@FROMDATE		VARCHAR(8)
DECLARE	@TODATE			VARCHAR(8)
DECLARE @CURRMONTH		VARCHAR(6)
DECLARE @LASTMONTH		VARCHAR(8)
DECLARE @LAST2MONTH		VARCHAR(8)
DECLARE @TDLAST3MONTH	VARCHAR(8)
DECLARE @LAST3MONTH		VARCHAR(8)

-----------------------------------------------------------------------------------
---set @TODATE = '20170916' 
SET @TODATE    = (SELECT CONVERT(VARCHAR(8),MAX(BUSINESS_DATE),112) FROM M74.BICDATA.DBO.BALANCE_LIVE)
SET @FROMDATE  = (SELECT CONVERT(VARCHAR(8),DATEADD(mm,DATEDIFF(mm,0,@TODATE),0),112))
-------------------------------------------------
SET @TODATE_1   = (SELECT CONVERT(VARCHAR(8),DATEADD(ms,-3,DATEADD(mm,0,DATEADD(mm,DATEDIFF(mm,0,@TODATE),0))),112)) 
SET @FROMDATE_1 = (SELECT CONVERT(VARCHAR(8),DATEADD(mm,-1,DATEADD(mm,DATEDIFF(mm,0,@TODATE),0)),112)) 
--------------

SET @CURRMONTH = LEFT(@TODATE , 6) 
SET @LASTMONTH     = CONVERT(VARCHAR(8),DATEADD(MS,-3,DATEADD(MM,0,DATEADD(MM,DATEDIFF(MM,0,@TODATE),0))),112) 
SET @LAST2MONTH    = CONVERT(VARCHAR(8),DATEADD(MS,-3,DATEADD(MM,-1,DATEADD(MM,DATEDIFF(MM,0,@TODATE),0))),112)
SET @TDLAST3MONTH  = CONVERT(VARCHAR(8),DATEADD(M,-3,CONVERT(DATE,@TODATE)),112)
SET @LAST3MONTH    = CONVERT(VARCHAR(8),DATEADD(MS,-3,DATEADD(MM,-2,DATEADD(MM,DATEDIFF(MM,0,@TODATE),0))),112)


-----------------------CHAY CODE NAY NGAY DAU THANG DE UPDATE SO CHOT THANG TRUOC
EXEC('
UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET NEW_PRE = B.MTD,
		TOTAL_PRE = B.TOTAL_CUR
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, DBS_DAILY.DBO.DAILY_DBS_REPORT_'+@LASTMONTH+' B
			WHERE A.NO = B.NO
			AND A.ITEM = B.ITEM
			AND A.TYPE = B.TYPE
')

----------------------UPDATE KPI THANG NGAY DAU THANG
EXEC('
UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
				SET CUR_TARGET = CASE 
						WHEN ITEM = ''TOTAL_USER''						THEN  (select Amt from DATA..DBS_Budget_2017 
																				where  Indicator = ''Total user'' and Rptmonth  = '''+@CURRMONTH+''' ) 
						  WHEN ITEM = ''Ty le active user''				THEN  (select Amt from DATA..DBS_Budget_2017 
																				where  Indicator = ''Active User'' and Rptmonth  = '''+@CURRMONTH+''' ) 
						  WHEN ITEM = ''Total_TD'' AND TYPE = ''Bal''	THEN  (select Amt from DATA..DBS_Budget_2017 
																				where  Indicator = ''TD Online Balance'' and Rptmonth  = '''+@CURRMONTH+''' ) 
					      WHEN ITEM = ''Ty le TD''						THEN   (select Amt from DATA..DBS_Budget_2017 
																				where  Indicator = ''TD Online Rate'' and Rptmonth  = '''+@CURRMONTH+''' ) 
						  WHEN ITEM = ''Total_Loan''					THEN   (select sum(Amt) from DATA..DBS_Budget_2017 
																				where  Indicator = ''New Online Loan Contract'' and Rptmonth  <= '''+@CURRMONTH+''' ) 
					 ELSE NULL
					 END 
')


EXEC('
-----------------------------------------------------------------------------------------
UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET FTD = 0,
		MTD = 0,
		TOTAL_CUR = 0,
		NET_INCREASE = 0,
		[PERCENT] = 0,
		REMAINING = 0


UPDATE DBS_DAILY.DBO.DAILY_DBS_TRANS
	SET Pre_ID = 0,
		MTD_ID = 0,
		Net_increase_ID = 0,
		Pre_Bal = 0,
		MTD_Bal = 0,
		Net_increase_Bal = 0
	')


EXEC('
-- I. MTD --------------------------------------------------
-- 0. FTD
-------------------------------------------------TOTAL USER------------------------------------------------
SELECT * INTO #FTD_NEW_USER FROM 
	(
	SELECT  ''NEW USER'' [ITEM],''I2B'' [ITEM_DETAIL], (
		(SELECT COUNT(1) ID  FROM DBS_DAILY.DBO.TBL_I2B_USERS_F0_'+@TODATE+'
		WHERE AMND_STATE IN (''A'') 		
		AND CONVERT(VARCHAR,OPEN_DATE,112) = '''+@TODATE+'''
		) 
		+
		(SELECT COUNT(DISTINCT CUST_CIF) ID  FROM DBS_DAILY.DBO.TBL_B2B_USERS_'+@TODATE+'
		WHERE AMND_STATUS IN (''A'') 		
		AND CONVERT(VARCHAR,OPEN_DATE,112) = '''+@TODATE+'''
		AND SEGMENT = ''SMEs'' 
		) 
			)  ''ID''
	UNION ALL
	SELECT ''NEW USER'' [ITEM], ''MOBILE BANKING'' [ITEM_DETAIL],COUNT(1) ID  FROM DBS_DAILY.DBO.TBL_I2B_MBANKING_ACC_'+@TODATE+'
		WHERE AMND_STATE IN (''A'') 
		--AND PROCESS_STATUS = ''FIN''
		AND CONVERT(VARCHAR,REGISTER_DATE,112) = '''+@TODATE+'''
		AND (BI_CHANNEL <> ''OTHER'' OR SEGMENT = ''SMES'')
	UNION ALL
	SELECT ''NEW USER'' [ITEM], ''TIMO'' [ITEM_DETAIL],COUNT(1) ID  FROM DBS_DAILY.DBO.CUSTOMER_'+@TODATE+' 
		WHERE COMPANY_BOOK= ''VN0010348''		
			AND BI_CHANNEL <> ''OTHER''
			AND CUST_TYPE IN (''60'')
			AND CONVERT(VARCHAR,CUS_OPEN_DATE,112) = '''+@TODATE+'''
	UNION ALL
	SELECT ''NEW USER'' [ITEM], ''MOCA'' [ITEM_DETAIL],COUNT(1) ID  FROM DBS_DAILY.DBO.MOCA_USERS_'+@TODATE+'
		WHERE CONVERT(VARCHAR,FIRST_TRANS_DATE,112) = '''+@TODATE+''') A


-- UPDATE
UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET FTD = B.ID
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #FTD_NEW_USER B
			WHERE A.ITEM = B.ITEM_DETAIL
			

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET FTD = (SELECT SUM(FTD) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''I2B'',''MOBILE BANKING'',''TIMO'',''MOCA''))
		WHERE ITEM = ''TOTAL_USER''


-- 1. MTD_NEW_USER
-- RUN
SELECT * INTO #MTD_NEW_USER FROM 
	(
	SELECT  ''NEW USER'' [ITEM],''I2B'' [ITEM_DETAIL], (
		(SELECT COUNT(1) ID  FROM DBS_DAILY.DBO.TBL_I2B_USERS_F0_'+@TODATE+'
		WHERE AMND_STATE IN (''A'') 
		AND CONVERT(VARCHAR,OPEN_DATE,112) >= '''+@FROMDATE+''' 
		AND CONVERT(VARCHAR,OPEN_DATE,112) <= '''+@TODATE+'''
		) 
		+
		(SELECT COUNT(DISTINCT CUST_CIF) ID  FROM DBS_DAILY.DBO.TBL_B2B_USERS_'+@TODATE+'
		WHERE AMND_STATUS IN (''A'') 
		AND CONVERT(VARCHAR,OPEN_DATE,112) >= '''+@FROMDATE+''' 
		AND CONVERT(VARCHAR,OPEN_DATE,112) <= '''+@TODATE+'''
		AND SEGMENT = ''SMEs''  
		) 
			)  ''ID''
	UNION ALL
	SELECT ''NEW USER'' [ITEM], ''MOBILE BANKING'' [ITEM_DETAIL],COUNT(1) ID  FROM DBS_DAILY.DBO.TBL_I2B_MBANKING_ACC_'+@TODATE+'
		WHERE AMND_STATE IN (''A'') 
		--AND PROCESS_STATUS = ''FIN''
		AND (BI_CHANNEL <> ''OTHER'' OR SEGMENT = ''SMES'')
		AND CONVERT(VARCHAR,REGISTER_DATE,112) >= '''+@FROMDATE+''' 
		AND CONVERT(VARCHAR,REGISTER_DATE,112) <= '''+@TODATE+'''
	UNION ALL
	SELECT ''NEW USER'' [ITEM], ''TIMO'' [ITEM_DETAIL],COUNT(1) ID  FROM DBS_DAILY.DBO.CUSTOMER_'+@TODATE+' 
		WHERE COMPANY_BOOK= ''VN0010348''		
			AND BI_CHANNEL <> ''OTHER''
			AND CUST_TYPE IN (''59'',''60'')
			AND CONVERT(VARCHAR,CUS_OPEN_DATE,112) >= '''+@FROMDATE+''' 
			AND CONVERT(VARCHAR,CUS_OPEN_DATE,112) <= '''+@TODATE+'''
	UNION ALL
	SELECT ''NEW USER'' [ITEM], ''MOCA'' [ITEM_DETAIL],COUNT(1) ID  FROM DBS_DAILY.DBO.MOCA_USERS_'+@TODATE+'
		WHERE CONVERT(VARCHAR,FIRST_TRANS_DATE,112) >= '''+@FROMDATE+'''
		AND CONVERT(VARCHAR,FIRST_TRANS_DATE,112) <= '''+@TODATE+''') A


-- UPDATE
UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET MTD = B.ID
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #MTD_NEW_USER B
			WHERE A.ITEM = B.ITEM_DETAIL
			

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET MTD = (SELECT SUM(MTD) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''I2B'',''MOBILE BANKING'',''TIMO'',''MOCA''))
		WHERE ITEM = ''TOTAL_USER''


-- 2. TOTAL USER CURR
-- RUN
SELECT * INTO #TOTAL_CUR_USER FROM 
	(
	SELECT  ''TOTAL USER'' [ITEM],''I2B'' [ITEM_DETAIL], (
		(SELECT COUNT(1) ID  FROM DBS_DAILY.DBO.TBL_I2B_USERS_F0_'+@TODATE+'	WHERE AMND_STATE IN (''A'') 
		) 
		+
		(SELECT COUNT(DISTINCT CUST_CIF) ID  FROM DBS_DAILY.DBO.TBL_B2B_USERS_'+@TODATE+' WHERE AMND_STATUS IN (''A'') AND SEGMENT = ''SMEs'' 		
		) 
			)  ''ID''
	UNION ALL
	SELECT ''TOTAL USER'' [ITEM], ''MOBILE BANKING'' [ITEM_DETAIL],COUNT(1) ID  FROM DBS_DAILY.DBO.TBL_I2B_MBANKING_ACC_'+@TODATE+' WHERE (BI_CHANNEL <> ''OTHER'' OR SEGMENT = ''SMES'')
	UNION ALL
	SELECT ''TOTAL USER'' [ITEM], ''TIMO'' [ITEM_DETAIL],COUNT(1) ID  FROM DBS_DAILY.DBO.CUSTOMER_'+@TODATE+' 
		WHERE COMPANY_BOOK= ''VN0010348''		
			AND BI_CHANNEL <> ''OTHER''
			AND CUST_TYPE IN (''59'',''60'')
			AND CONVERT(VARCHAR,CUS_OPEN_DATE,112) <= '''+@TODATE+'''
	UNION ALL
	SELECT ''TOTAL USER'' [ITEM], ''MOCA'' [ITEM_DETAIL],COUNT(DISTINCT T24_CIF) ID FROM DBS_DAILY.DBO.MOCA_TRANSACTION_'+@TODATE+'
		WHERE CARD_STATUS = ''CARD OK''
			AND CONTRACT_STATUS = ''ACCOUNT OK''
			AND BI_SEGMENT IN (''KHCN'',''SMEs'')
			AND CONVERT(VARCHAR,TRANS_DATE,112) <= '''+@TODATE+'''
	) A


-- UPDATE
UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = B.ID
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #TOTAL_CUR_USER B
			WHERE A.ITEM = B.ITEM_DETAIL
			

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = (SELECT SUM(TOTAL_CUR) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''I2B'',''MOBILE BANKING'',''TIMO'',''MOCA''))
		WHERE ITEM = ''TOTAL_USER''
')

----------------------------------------------------ACTIVE USERS------------------------------------------------
		
EXEC
('
--7.1. Active i2b users
SELECT *
	INTO #USERS_ACTIVE 
		FROM 
(
SELECT ''Total user'' [ITEM], ''Active i2b'' [ITEM_DETAIL], COUNT(DISTINCT CIF) ID  FROM
(
SELECT DISTINCT CIF
		FROM DBS_DAILY.DBO.EBANKING_TRANSACTION_'+@TODATE+'
			WHERE FINAL_STATUS = ''SUCCESSFUL''
				AND BI_CHANNEL <> ''OTHER''
				AND CHANNEL IN (''I2B'', ''MOMO'', ''ECOM'')
UNION ALL
SELECT DISTINCT CIF
		FROM DBS_MONTHLY.DBO.EBANKING_TRANSACTION_'+@LASTMONTH+'
			WHERE FINAL_STATUS = ''SUCCESSFUL''
				AND BI_CHANNEL <> ''OTHER''
				AND CHANNEL IN (''I2B'', ''MOMO'', ''ECOM'')
UNION ALL
SELECT DISTINCT CIF
		FROM DBS_MONTHLY.DBO.EBANKING_TRANSACTION_'+@LAST2MONTH+'
			WHERE FINAL_STATUS = ''SUCCESSFUL''
				AND BI_CHANNEL <> ''OTHER''
				AND CHANNEL IN (''I2B'', ''MOMO'', ''ECOM'')

UNION ALL
SELECT DISTINCT CIF
		FROM DBS_MONTHLY.DBO.EBANKING_TRANSACTION_'+@LAST3MONTH+'
			WHERE FINAL_STATUS = ''SUCCESSFUL''
				AND BI_CHANNEL <> ''OTHER''
				AND CHANNEL IN (''I2B'', ''MOMO'', ''ECOM'')
				AND CONVERT(VARCHAR(8),VALUE_DATE,112) > '''+@TDLAST3MONTH+'''
				AND CONVERT(VARCHAR(8),VALUE_DATE,112) < = '''+@LAST3MONTH+'''

UNION ALL
SELECT DISTINCT CUS_CIF FROM [DBS_DAILY].[DBO].[TBL_I2B_AUTH_INFO_'+@TODATE+'] AS T1
    WHERE CONVERT(DATE, T1.TIME_RQ) >  '''+@TDLAST3MONTH+'''
              AND CONVERT(DATE, T1.TIME_RQ) < = '''+@TODATE+'''
              AND CUS_CIF IN (SELECT T24_CIF FROM DBS_DAILY.DBO.TBL_I2B_USERS_F0_'+@TODATE+' WHERE AMND_STATE = ''A'')
			  AND CHANNEL_RQ = ''I2B''
UNION ALL 
SELECT DISTINCT T24_CIF 
	FROM DBS_DAILY.DBO.TBL_I2B_USERS_F0_'+@TODATE+'	
			WHERE AMND_STATE = ''A'' 
				AND OPEN_DATE > '''+@TDLAST3MONTH+'''	
) A
WHERE CIF IN (SELECT T24_CIF FROM DBS_DAILY.DBO.TBL_I2B_USERS_F0_'+@TODATE+' WHERE AMND_STATE = ''A'')

UNION ALL

--7.2. Active mobile banking users

SELECT ''Total user'' [ITEM], ''Active mobile banking'' [ITEM_DETAIL], COUNT(DISTINCT CIF) ID FROM
(
SELECT DISTINCT CIF
		FROM DBS_DAILY.DBO.EBANKING_TRANSACTION_'+@TODATE+'
			WHERE FINAL_STATUS = ''SUCCESSFUL''
				AND BI_CHANNEL <> ''OTHER''
				AND CHANNEL = ''MOBILE''
UNION ALL
SELECT DISTINCT CIF
		FROM DBS_MONTHLY.DBO.EBANKING_TRANSACTION_'+@LASTMONTH+'
			WHERE FINAL_STATUS = ''SUCCESSFUL''
				AND BI_CHANNEL <> ''OTHER''
				AND CHANNEL = ''MOBILE''
UNION ALL
SELECT DISTINCT CIF
		FROM DBS_MONTHLY.DBO.EBANKING_TRANSACTION_'+@LAST2MONTH+'
			WHERE FINAL_STATUS = ''SUCCESSFUL''
				AND BI_CHANNEL <> ''OTHER''
				AND CHANNEL = ''MOBILE''
UNION ALL
SELECT DISTINCT CIF
		FROM DBS_MONTHLY.DBO.EBANKING_TRANSACTION_'+@LAST3MONTH+'
			WHERE FINAL_STATUS = ''SUCCESSFUL''
				AND BI_CHANNEL <> ''OTHER''
				AND CHANNEL = ''MOBILE''
				AND CONVERT(VARCHAR(8),VALUE_DATE,112) > '''+@TDLAST3MONTH+'''
				AND CONVERT(VARCHAR(8),VALUE_DATE,112) < = '''+@LAST3MONTH+'''

UNION ALL
SELECT DISTINCT CUS_CIF FROM [DBS_DAILY].[DBO].[TBL_I2B_AUTH_INFO_'+@TODATE+'] AS T1
    WHERE CONVERT(DATE, T1.TIME_RQ) >  '''+@TDLAST3MONTH+'''
              AND CONVERT(DATE, T1.TIME_RQ) <= '''+@TODATE+'''
              and CUS_CIF in (SELECT T24_CIF FROM DBS_DAILY.DBO.TBL_I2B_MBANKING_ACC_'+@TODATE+' 
									WHERE AMND_STATE = ''A'' 
									--AND PROCESS_STATUS = ''FIN'' 
									AND (BI_CHANNEL <> ''OTHER'' OR SEGMENT = ''SMES''))
			  AND CHANNEL_RQ = ''Mobile''
) A
WHERE CIF IN (SELECT T24_CIF FROM DBS_DAILY.DBO.TBL_I2B_MBANKING_ACC_'+@TODATE+' 
					WHERE AMND_STATE = ''A'' 
					--AND PROCESS_STATUS = ''FIN'' 
					AND (BI_CHANNEL <> ''OTHER'' OR SEGMENT = ''SMES''))

--7.3. Active TIMO customer

UNION ALL

SELECT ''Total user'' [ITEM], ''Active TIMO'' [ITEM_DETAIL], COUNT(DISTINCT CIF) ID FROM
(
SELECT DISTINCT CIF
		FROM DBS_DAILY.DBO.EBANKING_TRANSACTION_'+@TODATE+'
			WHERE FINAL_STATUS = ''SUCCESSFUL''
				AND CHANNEL = ''TIMO''
UNION ALL
SELECT DISTINCT CIF
		FROM DBS_MONTHLY.DBO.EBANKING_TRANSACTION_'+@LASTMONTH+'
			WHERE FINAL_STATUS = ''SUCCESSFUL''
				AND CHANNEL = ''TIMO''
UNION ALL
SELECT DISTINCT CIF
		FROM DBS_MONTHLY.DBO.EBANKING_TRANSACTION_'+@LAST2MONTH+'
			WHERE FINAL_STATUS = ''SUCCESSFUL''
				AND CHANNEL = ''TIMO''
UNION ALL
SELECT DISTINCT CIF
		FROM DBS_MONTHLY.DBO.EBANKING_TRANSACTION_'+@LAST3MONTH+'
			WHERE FINAL_STATUS = ''SUCCESSFUL''
				AND CHANNEL = ''TIMO''
				AND CONVERT(VARCHAR(8),VALUE_DATE,112) > '''+@TDLAST3MONTH+'''
				AND CONVERT(VARCHAR(8),VALUE_DATE,112) < = '''+@LAST3MONTH+'''

) A
WHERE CIF IN (SELECT RECID FROM DBS_DAILY.DBO.CUSTOMER_'+@TODATE+' WHERE COMPANY_BOOK LIKE ''%VN0010348%'' AND CUST_TYPE IN (''60''))

--7.4. Active MOCA users

UNION ALL
SELECT ''Total user'' [ITEM], ''Active MOCA'' [ITEM_DETAIL], COUNT(DISTINCT T24_CIF) ID
	FROM DBS_DAILY.DBO.MOCA_TRANSACTION_'+@TODATE+'
		WHERE CARD_STATUS = ''Card OK''
			AND CONTRACT_STATUS = ''Account OK''
			AND CONVERT(VARCHAR(8),TRANS_DATE,112) >   '''+@TDLAST3MONTH+'''
			AND CONVERT(VARCHAR(8),TRANS_DATE,112) < = '''+@TODATE+'''

--7.5. Active B2B users

UNION ALL
SELECT ''Total user'' [ITEM], ''Active B2B'' [ITEM_DETAIL],COUNT (DISTINCT CIF) ID FROM
(
SELECT DISTINCT CIF
	FROM DBS_DAILY.DBO.EBANKING_TRANSACTION_'+@TODATE+'
		WHERE FINAL_STATUS = ''SUCCESSFUL''
			AND SEGMENT = ''SMES''
	UNION ALL
SELECT DISTINCT CIF
	FROM DBS_MONTHLY.DBO.EBANKING_TRANSACTION_'+@LASTMONTH+'
		WHERE FINAL_STATUS = ''SUCCESSFUL''
			AND SEGMENT = ''SMES''
	UNION ALL
SELECT DISTINCT CIF
	FROM DBS_MONTHLY.DBO.EBANKING_TRANSACTION_'+@LAST2MONTH+'
		WHERE FINAL_STATUS = ''SUCCESSFUL''
			AND SEGMENT = ''SMES''
	UNION ALL
SELECT DISTINCT CIF
		FROM DBS_MONTHLY.DBO.EBANKING_TRANSACTION_'+@LAST3MONTH+'
			WHERE FINAL_STATUS = ''SUCCESSFUL''
				AND SEGMENT = ''SMES''
				AND CONVERT(VARCHAR(8),VALUE_DATE,112) > '''+@TDLAST3MONTH+'''
				AND CONVERT(VARCHAR(8),VALUE_DATE,112) < = '''+@LAST3MONTH+'''
	UNION ALL
SELECT DISTINCT CUST_CIF
    FROM DBS_DAILY.[DBO].TBL_B2B_SESSION_INFO_'+@TODATE+'
            WHERE CONVERT(DATE, LOGIN_TIME) > '''+@TDLAST3MONTH+'''
                    AND CONVERT(DATE, LOGIN_TIME) < = '''+@TODATE+'''
					AND CUST_CIF IN (SELECT CUST_CIF FROM DBS_DAILY.DBO.TBL_B2B_USERS_'+@TODATE+' WHERE CUST_CIF IN (SELECT RECID FROM DBS_DAILY.DBO.CUSTOMER_'+@TODATE+' 
										WHERE SEGMENT = ''SMES'' AND CONVERT(VARCHAR(8),CUS_OPEN_DATE,112) <= '''+@TODATE+'''))
) A
WHERE CIF IN (SELECT CUST_CIF FROM DBS_DAILY.DBO.TBL_B2B_USERS_'+@TODATE+' WHERE CUST_CIF IN (SELECT RECID FROM DBS_DAILY.DBO.CUSTOMER_'+@TODATE+' 
										WHERE SEGMENT = ''SMES'' AND CONVERT(VARCHAR(8),CUS_OPEN_DATE,112) <= '''+@TODATE+'''))
) A

SELECT * INTO #ACTIVE_USERS
	FROM #USERS_ACTIVE 
UNION ALL
SELECT ''Active user'' [ITEM], ''Total active user'' [ITEM_DETAIL], SUM (ID) ID
	FROM #USERS_ACTIVE 

----UPDATE 

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = B.ID
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #ACTIVE_USERS B
			WHERE A.ITEM = B.ITEM_DETAIL
			AND A.ITEM <> ''Active I2B''

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = (SELECT SUM(ID) FROM #ACTIVE_USERS WHERE ITEM_DETAIL IN (''ACTIVE I2B'',''ACTIVE B2B''))
			WHERE ITEM = ''Active I2B''
			

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = (SELECT SUM(TOTAL_CUR) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN 
																(''Active I2B'',''Active MOBILE BANKING'',''Active TIMO'',''Active MOCA''))
		WHERE ITEM = ''ACTIVE_USER''

---------------------------------------------------ACTIVE USER RATIO-------------------------------------------

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = (SELECT TOTAL_CUR FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM = ''Active_user'')/
			  (SELECT TOTAL_CUR FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM = ''Total_user'')
		WHERE ITEM = ''Ty le active user''
')

-----------------------------------------------------TD ONLINE-------------------------------------------------
-- RUN
EXEC
('
SELECT * INTO #SAVING
	FROM 
	(
	SELECT ''ONLINE TD'' [ITEM], ''FTD NEW BALANCE'' [ITEM_DETAIL],SUM(BAL_QD)/1E9 VL, COUNT(1) ID FROM DBS_DAILY.DBO.DPTB_MASTER_'+@TODATE+'
		WHERE   CONVERT(VARCHAR,ISSUE_DATE,112) = '''+@TODATE+'''						
			AND
				(((BI_CHANNEL <> ''OTHER''
					AND F IS NULL
					AND PRODUCT_DETAIL LIKE ''%ONLINE%''
					AND PRODUCT_NAME LIKE ''2%''
					AND CCY <> ''XAU'')
					) 
				OR
				(BI_SEGMENT =''SME'' AND PRODUCT_NAME LIKE ''2%'' AND PRODUCT_CODE =''TD6014'')
				)	
	UNION ALL
	SELECT ''ONLINE TD'' [ITEM], ''MTD NEW BALANCE'' [ITEM_DETAIL],SUM(BAL_QD)/1E9 VL, COUNT(1) ID FROM DBS_DAILY.DBO.DPTB_MASTER_'+@TODATE+'
		WHERE   CONVERT(VARCHAR,ISSUE_DATE,112) >= '''+@FROMDATE+''' 
			AND CONVERT(VARCHAR,ISSUE_DATE,112) <= '''+@TODATE+'''						
			AND
				(((BI_CHANNEL <> ''OTHER''
					AND F IS NULL
					AND PRODUCT_DETAIL LIKE ''%ONLINE%''
					AND PRODUCT_NAME LIKE ''2%''
					AND CCY <> ''XAU'')
					) 
				OR
				(BI_SEGMENT =''SME'' AND PRODUCT_NAME LIKE ''2%'' AND PRODUCT_CODE =''TD6014'')
				)	
	UNION ALL
	SELECT ''ONLINE TD'' [ITEM], ''END BALANCE'' [ITEM_DETAIL],SUM(BAL_QD)/1E9 VL, COUNT(1) ID FROM DBS_DAILY.DBO.BALANCE_'+@TODATE+'
		WHERE CONVERT(VARCHAR,ISSUE_DATE,112) <= '''+@TODATE+'''				
			AND
				(((BI_CHANNEL <> ''OTHER''
					AND F IS NULL
					AND PRODUCT_DETAIL LIKE ''%ONLINE%''
					AND PRODUCT_NAME LIKE ''2%''
					AND CCY <> ''XAU'')
					) 
				OR
				(BI_SEGMENT =''SME'' AND PRODUCT_NAME LIKE ''2%'' AND PRODUCT_CODE =''TD6014'')
				)	
	UNION ALL
	SELECT ''TIMO TD'' [ITEM], ''FTD NEW BALANCE'' [ITEM_DETAIL],SUM(BAL_QD)/1E9 VL, COUNT(1) ID FROM DBS_DAILY.DBO.DPTB_MASTER_'+@TODATE+'
			WHERE   CONVERT(VARCHAR,ISSUE_DATE,112) = '''+@TODATE+'''						
				AND	BI_CHANNEL <> ''OTHER''
				AND F IS NULL			
				AND CCY <> ''XAU''	
				AND BRANCH_CODE = ''VN0010348'' 
				AND PRODUCT_NAME LIKE ''2%''	
	UNION ALL
	SELECT ''TIMO TD'' [ITEM], ''MTD NEW BALANCE'' [ITEM_DETAIL],SUM(BAL_QD)/1E9 VL, COUNT(1) ID FROM DBS_DAILY.DBO.DPTB_MASTER_'+@TODATE+'
			WHERE   CONVERT(VARCHAR,ISSUE_DATE,112) >= '''+@FROMDATE+''' 
				AND CONVERT(VARCHAR,ISSUE_DATE,112) <= '''+@TODATE+'''						
				AND	BI_CHANNEL <> ''OTHER''
				AND F IS NULL			
				AND CCY <> ''XAU''	
				AND BRANCH_CODE = ''VN0010348'' 
				AND PRODUCT_NAME LIKE ''2%''				
	UNION ALL		
	SELECT ''TIMO TD'' [ITEM], ''END BALANCE'' [ITEM_DETAIL],SUM(BAL_QD)/1E9 VL, COUNT(1) ID FROM DBS_DAILY.DBO.BALANCE_'+@TODATE+'
		WHERE CONVERT(VARCHAR,ISSUE_DATE,112) <= '''+@TODATE+'''				
			AND BI_CHANNEL <> ''OTHER''
			AND F IS NULL	
			AND CCY <> ''XAU''								
			AND BRANCH_CODE = ''VN0010348'' 
			AND PRODUCT_NAME LIKE ''2%''
	UNION ALL
		SELECT ''OFFLINE TD'' [ITEM], ''FTD NEW BALANCE'' [ITEM_DETAIL],SUM(BAL_QD)/1E9 VL, COUNT(1) ID FROM DBS_DAILY.DBO.DPTB_MASTER_'+@TODATE+'
		WHERE   CONVERT(VARCHAR,ISSUE_DATE,112) = '''+@TODATE+'''						
			AND
				(((BI_CHANNEL <> ''OTHER''
					AND F IS NULL
					AND PRODUCT_DETAIL NOT LIKE ''%ONLINE%''
					AND PRODUCT_NAME LIKE ''2%''
					AND CCY <> ''XAU''
					AND BRANCH_CODE <> ''VN0010348'')
					) 
				OR
				(BI_SEGMENT =''SME'' AND PRODUCT_NAME LIKE ''2%'' AND PRODUCT_CODE <> ''TD6014'')
				)	
	UNION ALL
	SELECT ''OFFLINE TD'' [ITEM], ''MTD NEW BALANCE'' [ITEM_DETAIL],SUM(BAL_QD)/1E9 VL, COUNT(1) ID FROM DBS_DAILY.DBO.DPTB_MASTER_'+@TODATE+'
		WHERE   CONVERT(VARCHAR,ISSUE_DATE,112) >= '''+@FROMDATE+''' 
			AND CONVERT(VARCHAR,ISSUE_DATE,112) <= '''+@TODATE+'''						
			AND
				(((BI_CHANNEL <> ''OTHER''
					AND F IS NULL
					AND PRODUCT_DETAIL NOT LIKE ''%ONLINE%''
					AND PRODUCT_NAME LIKE ''2%''
					AND CCY <> ''XAU''
					AND BRANCH_CODE <> ''VN0010348'')
					) 
				OR
				(BI_SEGMENT =''SME'' AND PRODUCT_NAME LIKE ''2%'' AND PRODUCT_CODE <> ''TD6014'')
				)	
	UNION ALL
	SELECT ''OFFLINE TD'' [ITEM], ''END BALANCE'' [ITEM_DETAIL],SUM(BAL_QD)/1E9 VL, COUNT(1) ID FROM DBS_DAILY.DBO.BALANCE_'+@TODATE+'
		WHERE CONVERT(VARCHAR,ISSUE_DATE,112) <= '''+@TODATE+'''				
			AND
				(((BI_CHANNEL <> ''OTHER''
					AND F IS NULL
					AND PRODUCT_DETAIL NOT LIKE ''%ONLINE%''
					AND PRODUCT_NAME LIKE ''2%''
					AND CCY <> ''XAU''
					AND BRANCH_CODE <> ''VN0010348'')
					) 
				OR
				(BI_SEGMENT =''SME'' AND PRODUCT_NAME LIKE ''2%'' AND PRODUCT_CODE <> ''TD6014'')
				)				
					
	) A


-- UPDATE
UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET FTD = B.VL
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #SAVING B
			WHERE A. ITEM = B.ITEM
			AND B.ITEM_DETAIL = ''FTD NEW BALANCE''
			AND A.TYPE = ''BAL''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET MTD = B.VL
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #SAVING B
			WHERE A. ITEM = B.ITEM
			AND B.ITEM_DETAIL = ''MTD NEW BALANCE''
			AND A.TYPE = ''BAL''
			 

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = B.VL
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #SAVING B
			WHERE A. ITEM = B.ITEM
			AND B.ITEM_DETAIL = ''END BALANCE''
			AND A.TYPE = ''BAL''

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET FTD = B.ID
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #SAVING B
			WHERE A. ITEM = B.ITEM
			AND B.ITEM_DETAIL = ''FTD NEW BALANCE''
			AND A.TYPE = ''NO''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET MTD = B.ID
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #SAVING B
			WHERE A. ITEM = B.ITEM
			AND B.ITEM_DETAIL = ''MTD NEW BALANCE''
			AND A.TYPE = ''NO''
			 

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = B.ID
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #SAVING B
			WHERE A. ITEM = B.ITEM
			AND B.ITEM_DETAIL = ''END BALANCE''
			AND A.TYPE = ''NO''


--UPDATE TOTAL_TD

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET FTD = (SELECT SUM(FTD) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''ONLINE TD'',''TIMO TD'') AND TYPE = ''BAL'')
		WHERE ITEM = ''TOTAL_TD'' AND TYPE = ''BAL''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET MTD = (SELECT SUM(MTD) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''ONLINE TD'',''TIMO TD'') AND TYPE = ''BAL'')
		WHERE ITEM = ''TOTAL_TD'' AND TYPE = ''BAL''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = (SELECT SUM(TOTAL_CUR) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''ONLINE TD'',''TIMO TD'') AND TYPE = ''BAL'')
		WHERE ITEM = ''TOTAL_TD'' AND TYPE = ''BAL''

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET FTD = (SELECT SUM(FTD) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''ONLINE TD'',''TIMO TD'') AND TYPE = ''NO'')
		WHERE ITEM = ''TOTAL_TD'' AND TYPE = ''NO''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET MTD = (SELECT SUM(MTD) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''ONLINE TD'',''TIMO TD'') AND TYPE = ''NO'')
		WHERE ITEM = ''TOTAL_TD'' AND TYPE = ''NO''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = (SELECT SUM(TOTAL_CUR) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''ONLINE TD'',''TIMO TD'') AND TYPE = ''NO'')
		WHERE ITEM = ''TOTAL_TD'' AND TYPE = ''NO''


--UPDATE TOTAL_TD_VPB

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET FTD = ((SELECT SUM(FTD) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''ONLINE TD'',''TIMO TD'') AND TYPE = ''NO'')
				+
			   (SELECT ID FROM #SAVING WHERE ITEM = ''OFFLINE TD'' AND ITEM_DETAIL = ''FTD NEW BALANCE''))
		WHERE ITEM = ''TOTAL_TD_VPB'' AND TYPE = ''NO''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET MTD = ((SELECT SUM(MTD) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''ONLINE TD'',''TIMO TD'') AND TYPE = ''NO'')
			    +
			   (SELECT ID FROM #SAVING WHERE ITEM = ''OFFLINE TD'' AND ITEM_DETAIL = ''MTD NEW BALANCE''))
		WHERE ITEM = ''TOTAL_TD_VPB'' AND TYPE = ''NO''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = ((SELECT SUM(TOTAL_CUR) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''ONLINE TD'',''TIMO TD'') AND TYPE = ''NO'')
					 +
					 (SELECT ID FROM #SAVING WHERE ITEM = ''OFFLINE TD'' AND ITEM_DETAIL = ''MTD NEW BALANCE''))
		WHERE ITEM = ''TOTAL_TD_VPB'' AND TYPE = ''NO''


--UPDATE TY LE TD

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET FTD = (SELECT FTD FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM = ''Total_TD'' AND TYPE = ''NO'')/
			  (SELECT FTD FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM = ''Total_TD_VPB'' AND TYPE = ''NO'')
		WHERE ITEM = ''Ty le TD''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET MTD = (SELECT MTD FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM = ''Total_TD'' AND TYPE = ''NO'')/
			  (SELECT MTD FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM = ''Total_TD_VPB'' AND TYPE = ''NO'')
		WHERE ITEM = ''Ty le TD''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = (SELECT TOTAL_CUR FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM = ''Total_TD'' AND TYPE = ''NO'')/
				    (SELECT TOTAL_CUR FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM = ''Total_TD_VPB'' AND TYPE = ''NO'')
		WHERE ITEM = ''Ty le TD''
		
')
-- 4. OD ONLINE
-- RUN

EXEC
('
SELECT *
	INTO #OD
	FROM 
	(
	SELECT ''FTD NEW OD'' [ITEM], (CASE WHEN OVERDRAFT_TYPE = ''THAU CHI CBNV'' THEN ''THAU CHI CBNV'' 
								  WHEN OVERDRAFT_TYPE = ''THAU CHI CAM CO STK'' THEN ''THAU CHI CAM CO STK'' 
								  WHEN OVERDRAFT_TYPE = ''THAU CHI KH TIEU DUNG CASA'' THEN ''THAU CHI KH TIEU DUNG CASA''
								  ELSE ''THAU CHI CA NHAN TIEU DUNG'' END) [ITEM_DETAIL] ,COUNT(1) ID FROM DBS_DAILY.DBO.TBL_ONLINE_LOAN_'+@TODATE+'
									WHERE CONVERT(VARCHAR,REGIST_DATE,112) = '''+@TODATE+'''	
										GROUP BY (CASE WHEN OVERDRAFT_TYPE = ''THAU CHI CBNV'' THEN ''THAU CHI CBNV'' 
										  WHEN OVERDRAFT_TYPE = ''THAU CHI CAM CO STK'' THEN ''THAU CHI CAM CO STK'' 
										  WHEN OVERDRAFT_TYPE = ''THAU CHI KH TIEU DUNG CASA'' THEN ''THAU CHI KH TIEU DUNG CASA''
										  ELSE ''THAU CHI CA NHAN TIEU DUNG'' END)


	UNION ALL	
	SELECT ''MTD NEW OD'' [ITEM], (CASE WHEN OVERDRAFT_TYPE = ''THAU CHI CBNV'' THEN ''THAU CHI CBNV'' 
								  WHEN OVERDRAFT_TYPE = ''THAU CHI CAM CO STK'' THEN ''THAU CHI CAM CO STK'' 
								  WHEN OVERDRAFT_TYPE = ''THAU CHI KH TIEU DUNG CASA'' THEN ''THAU CHI KH TIEU DUNG CASA''
								  ELSE ''THAU CHI CA NHAN TIEU DUNG'' END) [ITEM_DETAIL] ,COUNT(1) ID FROM DBS_DAILY.DBO.TBL_ONLINE_LOAN_'+@TODATE+'
									WHERE CONVERT(VARCHAR,REGIST_DATE,112)   >= '''+@FROMDATE+'''	
										AND CONVERT(VARCHAR,REGIST_DATE,112) <= '''+@TODATE+'''	
										GROUP BY (CASE WHEN OVERDRAFT_TYPE = ''THAU CHI CBNV'' THEN ''THAU CHI CBNV'' 
										  WHEN OVERDRAFT_TYPE = ''THAU CHI CAM CO STK'' THEN ''THAU CHI CAM CO STK'' 
										  WHEN OVERDRAFT_TYPE = ''THAU CHI KH TIEU DUNG CASA'' THEN ''THAU CHI KH TIEU DUNG CASA''
										  ELSE ''THAU CHI CA NHAN TIEU DUNG'' END)
	UNION ALL	
	SELECT ''TOTAL OD'' [ITEM], (CASE WHEN OVERDRAFT_TYPE = ''THAU CHI CBNV'' THEN ''THAU CHI CBNV'' 
								  WHEN OVERDRAFT_TYPE = ''THAU CHI CAM CO STK'' THEN ''THAU CHI CAM CO STK'' 
								  WHEN OVERDRAFT_TYPE = ''THAU CHI KH TIEU DUNG CASA'' THEN ''THAU CHI KH TIEU DUNG CASA''
								  ELSE ''THAU CHI CA NHAN TIEU DUNG'' END) [ITEM_DETAIL] ,COUNT(1) ID FROM DBS_DAILY.DBO.TBL_ONLINE_LOAN_'+@TODATE+'
									 WHERE CONVERT(VARCHAR(4),REGIST_DATE,112) = CONVERT(VARCHAR(4),'''+@TODATE+''',112)
										GROUP BY (CASE WHEN OVERDRAFT_TYPE = ''THAU CHI CBNV'' THEN ''THAU CHI CBNV'' 
										  WHEN OVERDRAFT_TYPE = ''THAU CHI CAM CO STK'' THEN ''THAU CHI CAM CO STK'' 
										  WHEN OVERDRAFT_TYPE = ''THAU CHI KH TIEU DUNG CASA'' THEN ''THAU CHI KH TIEU DUNG CASA''
										  ELSE ''THAU CHI CA NHAN TIEU DUNG'' END)
	) A


-- UPDATE
UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET FTD = B.ID
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #OD B
			WHERE A. ITEM = B.ITEM_DETAIL
			AND B.ITEM = ''FTD NEW OD''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET MTD = B.ID
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #OD B
			WHERE A. ITEM = B.ITEM_DETAIL
			AND B.ITEM = ''MTD NEW OD''
			 

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = B.ID
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #OD B
			WHERE A. ITEM = B.ITEM_DETAIL
			AND B.ITEM = ''TOTAL OD''

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET FTD = (SELECT SUM(FTD) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''THAU CHI CA NHAN TIEU DUNG'',''THAU CHI CAM CO STK'',''THAU CHI CBNV'',''THAU CHI KH TIEU DUNG CASA''))
		WHERE ITEM = ''TOTAL_OD''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET MTD = (SELECT SUM(MTD) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''THAU CHI CA NHAN TIEU DUNG'',''THAU CHI CAM CO STK'',''THAU CHI CBNV'',''THAU CHI KH TIEU DUNG CASA''))
		WHERE ITEM = ''TOTAL_OD''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = (SELECT SUM(TOTAL_CUR) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''THAU CHI CA NHAN TIEU DUNG'',''THAU CHI CAM CO STK'',''THAU CHI CBNV'',''THAU CHI KH TIEU DUNG CASA''))
		WHERE ITEM = ''TOTAL_OD''
		

-- 5. CARD ONLINE
-- RUN
SELECT *
	INTO #CARD
		FROM 
		(
		SELECT ''FTD NEW CARD'' [ITEM],BI_CARD_TYPE [ITEM_DETAIL],COUNT(1) ID
			FROM DBS_DAILY.DBO.CARD_'+@TODATE+'
				WHERE CONVERT(VARCHAR,CARD_DATE_OPEN,112) = '''+@TODATE+'''	
				AND BI_CARD_TYPE IN (''TIMO CARD'',''ONLINE CARD'',''DIGITAL CARD'')	
					GROUP BY BI_CARD_TYPE
		UNION ALL
		SELECT ''MTD NEW CARD'' [ITEM],BI_CARD_TYPE [ITEM_DETAIL],COUNT(1) ID
			FROM DBS_DAILY.DBO.CARD_'+@TODATE+'
				WHERE   CONVERT(VARCHAR,CARD_DATE_OPEN,112) >= '''+@FROMDATE+''' 
					AND CONVERT(VARCHAR,CARD_DATE_OPEN,112) <= '''+@TODATE+'''	
					AND BI_CARD_TYPE IN (''TIMO CARD'',''ONLINE CARD'',''DIGITAL CARD'')		
						GROUP BY BI_CARD_TYPE
		UNION ALL
		SELECT ''TOTAL CARD'' [ITEM],BI_CARD_TYPE [ITEM_DETAIL],COUNT(1) ID
			FROM DBS_DAILY.DBO.CARD_'+@TODATE+'
				WHERE   CONVERT(VARCHAR,CARD_DATE_OPEN,112) <= '''+@TODATE+'''	
				AND CONVERT(VARCHAR(4),CARD_DATE_OPEN,112) = YEAR('''+@TODATE+''')	
				AND BI_CARD_TYPE IN (''TIMO CARD'',''ONLINE CARD'',''DIGITAL CARD'')	
						GROUP BY BI_CARD_TYPE
		) A

	
-- UPDATE
UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET FTD = B.ID
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #CARD B
			WHERE A. ITEM = B.ITEM_DETAIL
			AND B.ITEM = ''FTD NEW CARD''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET MTD = B.ID
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #CARD B
			WHERE A. ITEM = B.ITEM_DETAIL
			AND B.ITEM = ''MTD NEW CARD''
			 

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = B.ID
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #CARD B
			WHERE A. ITEM = B.ITEM_DETAIL
			AND B.ITEM = ''TOTAL CARD''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET FTD = (SELECT SUM(FTD) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''TIMO CARD'',''ONLINE CARD'',''DIGITAL CARD''))
		WHERE ITEM = ''TOTAL_CARD''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET MTD = (SELECT SUM(MTD) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''TIMO CARD'',''ONLINE CARD'',''DIGITAL CARD''))
		WHERE ITEM = ''TOTAL_CARD''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = (SELECT SUM(TOTAL_CUR) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''TIMO CARD'',''ONLINE CARD'',''DIGITAL CARD''))
		WHERE ITEM = ''TOTAL_CARD''
')

----------------------------------

-- 5. UPL ONLINE
-- RUN
--SELECT * FROM DBS_DAILY.DBO.UPL24_20170206

EXEC
('
SELECT *
	INTO #UPL
		FROM 
		(
		SELECT ''FTD NEW UPL'' [ITEM], ''UPL'' [ITEM_DETAIL],COUNT(1) ID
			FROM DBS_DAILY.DBO.UPL24_'+@TODATE+'
				WHERE CONVERT(VARCHAR,VALUE_DATE,112) = '''+@TODATE+'''			
		UNION ALL
		SELECT ''MTD NEW UPL'' [ITEM],''UPL'' [ITEM_DETAIL],COUNT(1) ID
			FROM DBS_DAILY.DBO.UPL24_'+@TODATE+'
				WHERE   CONVERT(VARCHAR,VALUE_DATE,112) >= '''+@FROMDATE+''' 
					AND CONVERT(VARCHAR,VALUE_DATE,112) <= '''+@TODATE+'''			
		UNION ALL
		SELECT ''TOTAL UPL'' [ITEM],''UPL'' [ITEM_DETAIL],COUNT(1) ID
			FROM DBS_DAILY.DBO.UPL24_'+@TODATE+'
				WHERE   CONVERT(VARCHAR,VALUE_DATE,112) <= '''+@TODATE+'''	
				AND CONVERT(VARCHAR(4),VALUE_DATE,112) = YEAR('''+@TODATE+''')		
		) A

		

-- UPDATE
UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET FTD = B.ID
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #UPL B
			WHERE A. ITEM = B.ITEM_DETAIL
			AND B.ITEM = ''FTD NEW UPL''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET MTD = B.ID
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #UPL B
			WHERE A. ITEM = B.ITEM_DETAIL
			AND B.ITEM = ''MTD NEW UPL''
			 

UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = B.ID
		FROM DBS_DAILY.DBO.DAILY_DBS_REPORT A, #UPL B
			WHERE A. ITEM = B.ITEM_DETAIL
			AND B.ITEM = ''TOTAL UPL''

')
		

-- 6. TOTAL LOAN
EXEC
('
UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET FTD = (SELECT SUM(FTD) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''Total_OD'',''Total_Card'',''UPL''))
		WHERE ITEM = ''TOTAL_LOAN''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET MTD = (SELECT SUM(MTD) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''Total_OD'',''Total_Card'',''UPL''))
		WHERE ITEM = ''TOTAL_LOAN''


UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET TOTAL_CUR = (SELECT SUM(TOTAL_CUR) FROM DBS_DAILY.DBO.DAILY_DBS_REPORT WHERE ITEM IN (''Total_OD'',''Total_Card'',''UPL''))
		WHERE ITEM = ''TOTAL_LOAN''
		

 -- 7. NET INCREASE
 UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET NET_INCREASE = TOTAL_CUR - TOTAL_PRE
		WHERE ITEM <> ''TY LE TD''

 UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET NET_INCREASE = MTD - NEW_PRE
		WHERE ITEM = ''TY LE TD''
	

 UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET [PERCENT] = TOTAL_CUR /CUR_TARGET WHERE CUR_TARGET > 0
		 AND ITEM <> ''TY LE TD''
	 
 UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET [PERCENT] = MTD /CUR_TARGET
		WHERE ITEM = ''TY LE TD''


 UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET REMAINING = YTD_TARGET - TOTAL_CUR WHERE YTD_TARGET > 0
		AND ITEM <> ''TY LE TD''


 UPDATE DBS_DAILY.DBO.DAILY_DBS_REPORT
	SET REMAINING = YTD_TARGET - MTD
		WHERE ITEM = ''TY LE TD''


-- 6. TAO BANG MOI

IF EXISTS (SELECT * FROM DBS_DAILY.DBO.SYSOBJECTS WHERE NAME = ''DAILY_DBS_REPORT_'+@TODATE+''')
	DROP TABLE [DBS_DAILY].[DBO].[DAILY_DBS_REPORT_'+@TODATE+']


SELECT * INTO DBS_DAILY.DBO.DAILY_DBS_REPORT_'+@TODATE+' FROM DBS_DAILY.DBO.DAILY_DBS_REPORT
')

---------------------------------------------------------------------------------------------
-- II. TRANSACTION --------------------------------------------------------------------
-- RUN
EXEC('
SELECT TRANS_TYPE_GROUP [GROUP],TRANS_TYPE ITEM,COUNT(1) PRE_ID,SUM(TXN_AMT)/1E9 PRE_BAL 
	INTO #PRE_TRANS
		FROM DBS_MONTHLY.DBO.EBANKING_TRANSACTION_'+@TODATE_1+'
			WHERE FINAL_STATUS = ''SUCCESSFUL''
				AND (BI_CHANNEL <> ''OTHER'' OR SEGMENT = ''SMES'')
				AND CONVERT(VARCHAR,VALUE_DATE,112) >= '''+@FROMDATE_1+''' 
				AND CONVERT(VARCHAR,VALUE_DATE,112) <= '''+@TODATE_1+''' 
					GROUP BY TRANS_TYPE_GROUP,TRANS_TYPE
					ORDER BY TRANS_TYPE_GROUP,TRANS_TYPE


SELECT TRANS_TYPE_GROUP [GROUP],TRANS_TYPE ITEM,COUNT(1) MTD_ID,SUM(TXN_AMT)/1E9 MTD_BAL 
	INTO #MTD_TRANS
		FROM DBS_DAILY.DBO.EBANKING_TRANSACTION_'+@TODATE+'
			WHERE FINAL_STATUS = ''SUCCESSFUL''
				AND (BI_CHANNEL <> ''OTHER'' OR SEGMENT = ''SMES'')
				AND CONVERT(VARCHAR,VALUE_DATE,112) >= '''+@FROMDATE+''' 
				AND CONVERT(VARCHAR,VALUE_DATE,112) <= '''+@TODATE+'''
					GROUP BY TRANS_TYPE_GROUP,TRANS_TYPE
					ORDER BY TRANS_TYPE_GROUP,TRANS_TYPE


-- UPDATE
UPDATE DBS_DAILY.DBO.DAILY_DBS_TRANS
	SET PRE_ID = 0, MTD_ID = 0, NET_INCREASE_ID = 0,
		PRE_BAL = 0, MTD_BAL = 0, NET_INCREASE_BAL = 0


UPDATE DBS_DAILY.DBO.DAILY_DBS_TRANS
	SET PRE_ID = B.PRE_ID,
		PRE_BAL = B.PRE_BAL
			FROM DBS_DAILY.DBO.DAILY_DBS_TRANS A, #PRE_TRANS B
				WHERE A.ITEM = B.ITEM
				AND A.[GROUP] = B.[GROUP]



UPDATE DBS_DAILY.DBO.DAILY_DBS_TRANS
	SET MTD_ID = B.MTD_ID,
		MTD_BAL = B.MTD_BAL
			FROM DBS_DAILY.DBO.DAILY_DBS_TRANS A, #MTD_TRANS B
				WHERE A.ITEM = B.ITEM
				AND A.[GROUP] = B.[GROUP]


-- TONG
UPDATE DBS_DAILY.DBO.DAILY_DBS_TRANS
	SET PRE_ID = (SELECT SUM(PRE_ID) FROM DBS_DAILY.DBO.DAILY_DBS_TRANS)
		WHERE ITEM = ''TOTAL''

UPDATE DBS_DAILY.DBO.DAILY_DBS_TRANS
	SET PRE_BAL = (SELECT SUM(PRE_BAL) FROM DBS_DAILY.DBO.DAILY_DBS_TRANS)
		WHERE ITEM = ''TOTAL''


UPDATE DBS_DAILY.DBO.DAILY_DBS_TRANS
	SET MTD_ID = (SELECT SUM(MTD_ID) FROM DBS_DAILY.DBO.DAILY_DBS_TRANS)
		WHERE ITEM = ''TOTAL''

UPDATE DBS_DAILY.DBO.DAILY_DBS_TRANS
	SET MTD_BAL = (SELECT SUM(MTD_BAL) FROM DBS_DAILY.DBO.DAILY_DBS_TRANS)
		WHERE ITEM = ''TOTAL''


-- NET INCREASE
UPDATE DBS_DAILY.DBO.DAILY_DBS_TRANS
	SET NET_INCREASE_ID = MTD_ID - PRE_ID


UPDATE DBS_DAILY.DBO.DAILY_DBS_TRANS
	SET NET_INCREASE_BAL = MTD_BAL - PRE_BAL


-- III. TAO RA BANG MOI --------------------------------------------------------------------

IF EXISTS (SELECT * FROM DBS_DAILY.DBO.SYSOBJECTS WHERE NAME = ''DAILY_DBS_TRANS_'+@TODATE+''')
	DROP TABLE [DBS_DAILY].[DBO].[DAILY_DBS_TRANS_'+@TODATE+']

	
SELECT * INTO DBS_DAILY.DBO.DAILY_DBS_TRANS_'+@TODATE+' FROM DBS_DAILY.DBO.DAILY_DBS_TRANS

')
 